name: Docker Build
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITOPS_REPO: ORG/REPO # CHANGE THIS
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{sha}}
            type=raw,value=latest
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
      - name: Attest
        uses: actions/attest-build-provenance@v4
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build-and-push
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ env.GITOPS_REPO }}
          ref: master
          ssh-key: ${{ secrets.GIT_SSH_KEY }}
          persist-credentials: true
      - name: Create GITHUB_SHA_SHORT
        id: meta
        run: |
          echo "github_sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      # ---------- install yq ----------
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        id: nix-cache
        with:
          primary-key: nix-${{ runner.os }}-nixos-25.11
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - name: Install yq
        run: nix profile install nixpkgs/nixos-25.11#yq-go
      # ---------- update image tag ----------
      - name: Update values.yaml
        run: |
          yq e -i '.containers[0].tag = "${{ steps.meta.outputs.github_sha_short }}"' kubernetes/deployments/backend.yaml
          yq e -i '.containers[0].tag = "${{ steps.meta.outputs.github_sha_short }}"' kubernetes/deployments/frontend.yaml
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update ev-dev to ${{ steps.meta.outputs.github_sha_short }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh: true
          branch: "master"
