name: Deploy to Cloudflare Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
env:
  PROJECT_NAME: project # CHANGE ME
  BUILD_DIR: dist # CHANGE ME
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install requirements
        run: yarn install
      - name: Build
        run: yarn build
      # ---------- publish ----------
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
