name: Python Test
on:
  pull_request:
    paths-ignore:
      - '.github/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Export requirements.txt
        run: |
          uv export --no-hashes --no-emit-project --output-file=requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run mlflow pipeline
        run: |
          python3 docker_mlflow/experiment_tracking.py
