name: Python Test
on:
  pull_request:
    paths-ignore:
      - '.github/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
      - name: Setup uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
          cache-python: true
      - name: Run mlflow pipeline
        run: |
          python3 docker_mlflow/experiment_tracking.py
