---
version: 2

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
checksum:
  disable: true
