repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/kahnwong/pre-commit
    rev: "db955a3"
    hooks:
      # -- go -- #
      - id: go-build
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-vet
      # -- ops -- #
      - id: yamlfmt
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
