---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REDIRECT_URL: ${REDIRECT_URL}
        API_BASE_URL: ${API_BASE_URL}
    image: foo
    environment:
      FOO: BAR
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data/app:/data
  # --------------- sidecar --------------- #
  init:
    build:
      context: .
    environment:
      RUN_MODE: init
    env_file:
      - .env
    depends_on:
      - postgres
