repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.12.1]
  - repo: https://github.com/kahnwong/pre-commit
    rev: "ecfbd9e"
    hooks:
      # -- go -- #
      - id: go-build
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: go-vet
      - id: golangci-lint
      # -- python -- #
      - id: ruff-check
      - id: ruff-format
      - id: uv-export
      - id: mypy
      - id: nbstripout
      # -- rust -- #
      - id: rust-fmt
      - id: cargo-check
      - id: cargo-clippy
      # -- terraform -- #
      - id: terraform-fmt
      - id: terraform-validate
      - id: terraform-docs
      - id: terraform-trivy
      # -- ops -- #
      - id: yamlfmt
      - id: yamllint
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
      - id: shellcheck
      - id: shfmt
      - id: trufflehog
      # -- misc -- #
      - id: nix-fmt
      - id: yarn-prettier
      - id: markdownlint-cli2
      - id: sqruff-lint
      - id: sqruff-fix
