repos:
  # ----------------------- OPS -----------------------
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: ^.github/dependabot.yaml
  #        exclude: (sops\.yaml)$
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_trivy
        args:
          - >
            --args=



              --skip-files="**/.terraform/**/*"
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
  # ----------------------- DOCS -----------------------
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        args: [--ignores, node_modules, src, --fix]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.12.1]
  # ----------------------- GOLANG -----------------------
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      # - id: no-go-testing
      - id: golangci-lint
      # - id: go-critic
      # - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  # ----------------------- NIX -----------------------
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: "nixfmt"
        language: system
  # ----------------------- NODE -----------------------
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: "yarn prettier . --write"
        language: system
  # ------------------------- PYTHON ------------------------
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402,E501"]
        exclude: ^migrations/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.15
    hooks:
      - id: uv-export
        args: [--no-hashes, --output-file=requirements.txt]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-black
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
  #  - repo: local
  #    hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: "poetry run mypy $PROJECT"
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       require_serial: true
  #  - repo: local
  #    hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest tests/tests.py
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       require_serial: true
  # ----------------------- RUST -----------------------
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
